server {
    listen 8080 ssl;
    server_name api.localhost;

    ssl_certificate /etc/nginx/ssl/backend.crt;
    ssl_certificate_key /etc/nginx/ssl/backend.key;

    location / {
        proxy_pass http://backend:4444;
    }
}
