server {
    listen 80;
    server_name localhost api.localhost;

    return 301 https://$host:8080$request_uri;
}

server {
    listen 8080 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/frontend.crt;
    ssl_certificate_key /etc/nginx/ssl/frontend.key;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://frontend:3000;
    }
}

# server {
#     listen 8080 ssl;
#     server_name api.localhost;

#     ssl_certificate /etc/nginx/ssl/backend.crt;
#     ssl_certificate_key /etc/nginx/ssl/backend.key;

#     location / {
#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection "upgrade";

#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

#         proxy_pass http://backend:4444;
#     }
# }