services:
  Frontend:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.front
    container_name: frontend
    image: frontend:0.1
    restart: always

    depends_on:
      - Backend
    networks:
      - monitoring
    volumes:
      - ./frontend:/var/www/nextApp
    command: sh -c "npm install && npm run dev"

  Backend:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.back
    container_name: backend
    image: backend:0.1
    restart: always

    networks:
      - monitoring
    depends_on:
      - Redis
    volumes:
      - ./backend:/var/www/Backend
    command: sh -c "npm install && nodemon server.js"

  Redis:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.redis
    container_name: redis
    image: redis:0.1
    restart: always

    networks:
      - monitoring


  waf:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.waf
      network: host
    container_name: waf
    image: waf:0.1
    ports:
      - "8080:8080"
    depends_on:
      - Frontend
      - Backend
    restart: always
    networks:
      - monitoring
    volumes:
      - ./infra/nginx.conf:/etc/nginx/sites-available/default
      - ./infra/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf

  vault:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.vault
    container_name: vault
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - monitoring
    volumes:
      - ./vault:/vault/data
      - ./vault.hcl:/vault/config/vault.hcl

networks:
  monitoring:
    driver: bridge

