server {
    listen 8080 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/frontend.crt;
    ssl_certificate_key /etc/nginx/ssl/frontend.key;

    location / {
        proxy_pass http://frontend:3000;
    }
}
