
FROM debian:latest


RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    lsb-release \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*


RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash -


RUN apt-get install -y nodejs


RUN node -v && npm -v


WORKDIR /var/www/Backend


COPY ./backend/package*.json ./


COPY ./backend/ .

RUN rm -rf node_modules
RUN npm install
RUN npm i better-sqlite3
RUN npm install -g nodemon

EXPOSE 4444

CMD ["nodemon", "server.js"]
