
FROM debian:latest


RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    lsb-release \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*


RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -


RUN apt-get install -y nodejs


RUN node -v && npm -v


WORKDIR /var/www/Backend


COPY ./backend/package*.json ./


RUN npm install
RUN npm install -g nodemon

COPY ./backend/ .


EXPOSE 4444

CMD ["nodemon", "server.js"]
