FROM debian:latest


RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    lsb-release \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*


RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash -


RUN apt-get install -y nodejs


RUN node -v && npm -v


WORKDIR /var/www/nextApp


COPY ./frontend/package*.json ./


RUN npm install

COPY ./frontend/ .

# RUN npm run build


EXPOSE 3000

CMD ["npm", "run" , "dev"]
